### ISSUE TITLE
Broken on Meilisearch v0.11

### ISSUE THREAD

**Issue by Geometrically** [Mubelotix/meilisearch-sdk#4]
As the title says, when using this SDK on 0.11 the thread panics with this error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown("{\"message\":\"Unsupported media type\",\"errorCode\":\"unsupported_media_type\",\"errorType\":\"invalid_request_error\",\"errorLink\":\"https://docs.meilisearch.com/error/unsupported_media_type\"}")', src/routes/search.rs:184:31
stack backtrace:`

**Comment by MarinPostma** [comment]
Hey @Geometrically! Thanks for the report, can give me repro steps and the bactrace so I can investigate?

Thanks!

**Comment by Mubelotix** [comment]
I didn't test the library with MeiliSearch 0.11 for now. I think you are experiencing a breaking change of MeiliSearch. I will fix this and implement the last few routes during the next week.

**Comment by Geometrically** [comment]
Alright! Thank you.

**Comment by Mubelotix** [comment]
Fixed! Since Meilisearch 0.11 switched to `actix-web`, the header `Content-Type` is now required for PUT and POST methods.
