### ISSUE TITLE
Error enum doesn't implement std::error::Error

### ISSUE THREAD

**Issue by Aeledfyr** [Mubelotix/meilisearch-sdk#7]
The error enum `meilisearch_sdk::errors::Error` doesn't implement `std::error::Error`, which makes it hard to integrate with other error handling systems such as `thiserror` and `anyhow`.  All it should require are `Display` and `Error` impls for the `Error` enum.

For better compatibility, it would also be useful to add an enum variant for `reqwest` errors, so that the `source` method can be implemented on the `Error` enum.  That would be a breaking change though, so it may be worth delaying until a `0.2` release is ready.

**Comment by Mubelotix** [comment]
That's right. The error enum is a draft and must be improved a lot. I will publish a 0.2 version soon and will include these improvements.

**Comment by LukasKalbertodt** [comment]
I'm not sure why this issue was closed. The referenced commit doesn't fix it and in version `0.15.0`, neither `errors::Error` nor `errors::MeilisearchError` implement `std::error::Error`. This makes it really inconvenient to do error handling properly.
